### PR TITLE
Update CNI plugins to v1.0.1

### PR DESCRIPTION
**Pull request by masa213f**
Update CNI plugins from v0.9.1 to ~v1.1.1~ v1.0.1.

`ip.SetupVethWithName` has a breaking change ([detail](https://github.com/containernetworking/plugins/commit/a3cde17fc0d0749a33fba2773c6b9cc218169114)) so I fixed a bit.
```
$ go build ./cmd/placemat2
# github.com/cybozu-go/placemat/v2/pkg/dcnet
pkg/dcnet/netns.go:138:56: not enough arguments in call to ip.SetupVethWithName
        have (string, string, int, ns.NetNS)
        want (string, string, int, string, ns.NetNS)
```

When update the pluging to v1.1.0 or 1.1.1, the e2e test will be error.
So I will keep it at v1.0.x.
https://github.com/cybozu-go/placemat/runs/6033738954?check_suite_focus=true
https://github.com/cybozu-go/placemat/runs/7246276015?check_suite_focus=true

Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

### CODE REVIEW

**Review by yokaze — APPROVED** [review]
LGTM
